/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ece.superkids.ui.user.panels;

import com.ece.superkids.questions.enums.QuestionCategory;
import com.ece.superkids.questions.enums.QuestionLevel;
import com.ece.superkids.users.entities.User;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import com.ece.superkids.ui.events.Session;

/**
 *
 * @author baris & prashant
 */
public class ScoresHistoryPanel extends javax.swing.JPanel {

    private QuestionLevel level;
    private List<QuestionCategory> category;
    private JTable table[] = new JTable[3];
    private User user;
    private Session session;
    /*   
     * Creates new form ScoresHistoryPanel
     */

    public ScoresHistoryPanel() {
        initComponents();
        //get session
        session = Session.aSession();
        //get user
        user = session.getLoggedInUser();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBounds(new java.awt.Rectangle(0, 0, 300, 300));
        setOpaque(false);

        jButton1.setLabel("Level 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setLabel("Level 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setLabel("Level 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton3)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2)
                    .add(jButton3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        level = QuestionLevel.LEVEL_1;
        category = level.getCategories();
        jTabbedPane1.removeAll();
        for (int i = 0; i < category.size(); i++) {
            
            Object data[][] = user.getHistory(level.getCategories().get(i), level);
            
            if(data != null)
            {
            
            String Columnname[] = {"Question", "Attempt 1", "Attempt 2", "Attempt 3", "Attempt 4", "Attempt 5"};

            table[i] = new JTable(data, Columnname);
            JScrollPane spTable = new JScrollPane(table[i]);

            jTabbedPane1.addTab(category.get(i).toString(), spTable);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        level = QuestionLevel.LEVEL_2;
        category = level.getCategories();
        jTabbedPane1.removeAll();
        for (int i = 0; i < category.size(); i++) {
            Object data[][] = user.getHistory(level.getCategories().get(i), level);
            if(data != null)
            {
            String Columnname[] = {"Question Number", "Attempt 1", "Attempt 2", "Attempt 3", "Attempt 4", "Attempt 5"};

            table[i] = new JTable(data, Columnname);
            JScrollPane spTable = new JScrollPane(table[i]);

            jTabbedPane1.addTab(category.get(i).toString(), spTable);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        level = QuestionLevel.LEVEL_3;
        category = level.getCategories();
        jTabbedPane1.removeAll();
        for (int i = 0; i < category.size(); i++) {
           
            Object data[][] = user.getHistory(level.getCategories().get(i), level);
            if(data != null)
            {
            String Columnname[] = {"Question Number", "Attempt 1", "Attempt 2", "Attempt 3", "Attempt 4", "Attempt 5"};

            table[i] = new JTable(data, Columnname);
            JScrollPane spTable = new JScrollPane(table[i]);

            jTabbedPane1.addTab(category.get(i).toString(), spTable);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
