/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package superkidsapplication;
/**
 *
 * @author davidOhayon
 */
public class OptionsPanel extends javax.swing.JPanel {

    /**
     * Creates new form OptionsPanel
     */
    public OptionsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        multipleChoiceButton = new javax.swing.JToggleButton();
        matchingButton = new javax.swing.JToggleButton();
        oddOneOutButton = new javax.swing.JToggleButton();
        allTypesButton = new javax.swing.JToggleButton();
        volumeSlider = new javax.swing.JSlider();
        volumeLabel = new javax.swing.JLabel();

        multipleChoiceButton.setText("Multiple Choice");
        multipleChoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleChoiceButtonActionPerformed(evt);
            }
        });

        matchingButton.setText("Matching");
        matchingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchingButtonActionPerformed(evt);
            }
        });

        oddOneOutButton.setText("Odd One Out");
        oddOneOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oddOneOutButtonActionPerformed(evt);
            }
        });

        allTypesButton.setText("All Types");
        allTypesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTypesButtonActionPerformed(evt);
            }
        });

        volumeLabel.setText("Volume");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(volumeSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(volumeLabel))
                .add(157, 157, 157))
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(allTypesButton)
                    .add(oddOneOutButton)
                    .add(multipleChoiceButton)
                    .add(matchingButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .add(multipleChoiceButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(oddOneOutButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(matchingButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(allTypesButton)
                .add(18, 18, 18)
                .add(volumeSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(volumeLabel)
                .add(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void multipleChoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleChoiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multipleChoiceButtonActionPerformed

    private void allTypesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTypesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allTypesButtonActionPerformed

    private void matchingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matchingButtonActionPerformed

    private void oddOneOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oddOneOutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oddOneOutButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton allTypesButton;
    private javax.swing.JToggleButton matchingButton;
    private javax.swing.JToggleButton multipleChoiceButton;
    private javax.swing.JToggleButton oddOneOutButton;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(NewGamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(NewGamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(NewGamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(NewGamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewGamePanel().setVisible(true);
            }
        });
    }
}
