/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package superkidsapplication;

/**
 *
 * @author Heng
 */
public class SubjectSelectionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SubjectSelectionJPanel
     */
    public SubjectSelectionJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        title = new javax.swing.JLabel();
        userphoto = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        subject1 = new javax.swing.JButton();
        subject2 = new javax.swing.JButton();
        subject3 = new javax.swing.JButton();
        subject4 = new javax.swing.JButton();
        subject5 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jLayeredPane1.setAlignmentX(0.0F);
        jLayeredPane1.setAlignmentY(0.0F);
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(800, 600));

        title.setFont(new java.awt.Font("Chalkduster", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 51));
        title.setText("Adventure island map");
        title.setBounds(170, 90, 520, 70);
        jLayeredPane1.add(title, javax.swing.JLayeredPane.DEFAULT_LAYER);

        userphoto.setForeground(new java.awt.Color(255, 255, 51));
        userphoto.setText("user photo");
        userphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userphoto.setBounds(660, 10, 60, 60);
        jLayeredPane1.add(userphoto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        username.setForeground(new java.awt.Color(255, 255, 51));
        username.setText("username");
        username.setBounds(730, 20, 61, 16);
        jLayeredPane1.add(username, javax.swing.JLayeredPane.DEFAULT_LAYER);

        score.setForeground(new java.awt.Color(255, 255, 0));
        score.setText("score");
        score.setBounds(740, 40, 34, 16);
        jLayeredPane1.add(score, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subject1.setText("jButton1");
        subject1.setBounds(120, 200, 120, 120);
        jLayeredPane1.add(subject1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subject2.setText("jButton2");
        subject2.setBounds(230, 350, 120, 120);
        jLayeredPane1.add(subject2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subject3.setText("jButton3");
        subject3.setBounds(350, 200, 120, 120);
        jLayeredPane1.add(subject3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subject4.setText("jButton4");
        subject4.setBounds(470, 350, 120, 120);
        jLayeredPane1.add(subject4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subject5.setText("jButton5");
        subject5.setBounds(580, 200, 120, 120);
        jLayeredPane1.add(subject5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SubjectSelectionPanelResources/map_800_600.png"))); // NOI18N
        background.setText("jLabel5");
        background.setBounds(0, 0, 800, 600);
        jLayeredPane1.add(background, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel score;
    private javax.swing.JButton subject1;
    private javax.swing.JButton subject2;
    private javax.swing.JButton subject3;
    private javax.swing.JButton subject4;
    private javax.swing.JButton subject5;
    private javax.swing.JLabel title;
    private javax.swing.JLabel username;
    private javax.swing.JLabel userphoto;
    // End of variables declaration//GEN-END:variables
}
