/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package superkidsapplication.panels;

import com.ece.superkids.enums.QuestionLevel;
import superkidsapplication.controllers.PanelController;

/**
 *
 * @author baris
 */
public class NewGamePanel extends javax.swing.JPanel {

    /**
     * Creates new form NewGamePanel
     */
    private MainFrame mainFrame;
    private PanelController controller;
    
    public NewGamePanel() {
        controller=PanelController.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        level4Button = new javax.swing.JButton();
        level3Button = new javax.swing.JButton();
        level5Button = new javax.swing.JButton();
        level2Button = new javax.swing.JButton();
        level1Button = new javax.swing.JButton();
        backgoundLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));

        level4Button.setText("Level 4");
        level4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level4ButtonActionPerformed(evt);
            }
        });
        level4Button.setBounds(210, 470, 88, 29);
        jLayeredPane1.add(level4Button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        level3Button.setText("Level 3");
        level3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level3ButtonActionPerformed(evt);
            }
        });
        level3Button.setBounds(580, 320, 88, 29);
        jLayeredPane1.add(level3Button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        level5Button.setText("Level 5");
        level5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level5ButtonActionPerformed(evt);
            }
        });
        level5Button.setBounds(450, 470, 88, 29);
        jLayeredPane1.add(level5Button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        level2Button.setText("Level 2");
        level2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level2ButtonActionPerformed(evt);
            }
        });
        level2Button.setBounds(340, 320, 88, 29);
        jLayeredPane1.add(level2Button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        level1Button.setText("Level 1");
        level1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level1ButtonActionPerformed(evt);
            }
        });
        level1Button.setBounds(100, 320, 88, 29);
        jLayeredPane1.add(level1Button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgoundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/newgamebackground.png"))); // NOI18N
        backgoundLabel.setBounds(0, 0, 800, 600);
        jLayeredPane1.add(backgoundLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 719, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //FOR EACH LEVEL I THINK WE SHOULD HAVE A DIFFERENT PANEL RATHER THAN USING THE SAME PANEL
    
    private void level2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level2ButtonActionPerformed
        // TODO add your handling code here:
        SubjectSelectionPanel sPanel = new SubjectSelectionPanel(QuestionLevel.LEVEL_2);
        //add questionPanel
        controller.addPanel(sPanel);
    }//GEN-LAST:event_level2ButtonActionPerformed

    private void level1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level1ButtonActionPerformed
        // TODO add your handling code here
          
        //CATEGORIES PANEL COMES HERE.
        //QUESTIONS PANEL WILL BE ACCESSED FROM CATEGORIESPANEL
        SubjectSelectionPanel sPanel = new SubjectSelectionPanel(QuestionLevel.LEVEL_1);
        //add questionPanel
        controller.addPanel(sPanel);      
    }//GEN-LAST:event_level1ButtonActionPerformed

    private void level3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level3ButtonActionPerformed
        // TODO add your handling code here:
        //SubjectSelectionPanel sPanel = new SubjectSelectionPanel("LEVEL_3");
        //add questionPanel
        //controller.addPanel(sPanel);
    }//GEN-LAST:event_level3ButtonActionPerformed

    private void level4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level4ButtonActionPerformed
        // TODO add your handling code here:
        //SubjectSelectionPanel sPanel = new SubjectSelectionPanel("LEVEL_4");
        //add questionPanel
        //controller.addPanel(sPanel);
    }//GEN-LAST:event_level4ButtonActionPerformed

    private void level5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level5ButtonActionPerformed
        // TODO add your handling code here:
        //SubjectSelectionPanel sPanel = new SubjectSelectionPanel("LEVEL_5");
        //add questionPanel
        //controller.addPanel(sPanel);
    }//GEN-LAST:event_level5ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgoundLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton level1Button;
    private javax.swing.JButton level2Button;
    private javax.swing.JButton level3Button;
    private javax.swing.JButton level4Button;
    private javax.swing.JButton level5Button;
    // End of variables declaration//GEN-END:variables
}
