/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package superkidsapplication.panels;

import com.ece.superkids.questions.enums.QuestionCategory;

import javax.swing.*;

import superkidsapplication.video.VideoPlayer;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author FRANKs
 */
public class TutorialPanel extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form TutorialPanel
     */

    private static VideoPlayer player;
    private String fileName;
    private static JButton play;

    public TutorialPanel(QuestionCategory category) {
        this.setName("Learning");
        initComponents();
        jLabel1.setText(category.toString());
        player = new VideoPlayer();

        play = new JButton("Play");
        play.setBounds(80, 80, 40, 40);
        play.addActionListener(this);
        JPanel panel = player.getViewingPanel();
        panel.setBackground(Color.BLACK);
        panel.setBounds(80, 180, panel.getPreferredSize().width, panel.getPreferredSize().height);
        jLayeredPane1.add(panel, JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(play, JLayeredPane.POPUP_LAYER);

        switch (category) {
            case SHAPES:
                fileName = "/videos/shapes.mp4";
                break;
            case COLORS:
                fileName = "/videos/colors.mp4";
                break;
            case ANIMALS:
                fileName = "/videos/animals.mp4";
                break;
            default:
        }

    }

    public void play() {
        long time = System.currentTimeMillis();
        player.play(fileName);
        System.out.println(System.currentTimeMillis() - time);
        time = System.currentTimeMillis();
        repaint();
        System.out.println("Repaint");
        player.run();
        System.out.println(System.currentTimeMillis() - time);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setBounds(0, 90, 800, 60);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/QuestionScreen.png"))); //
        // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBounds(0, 0, 800, 600);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables

    public static void main(String [] args) {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        TutorialPanel panel = new TutorialPanel(QuestionCategory.SHAPES);
        frame.add(panel);
        frame.pack();
        //play.setEnabled(false);
        frame.setVisible(true);
        panel.play();

        //play.setEnabled(true);
    }

    @Override
    public void actionPerformed(final ActionEvent e) {
       play();
    }
}
