/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ece.superkids.ui.parent.panels;

import com.ece.superkids.ui.parent.panels.ResetGamePanel;
import com.ece.superkids.ui.parent.panels.AddQuestionPanel;
import com.ece.superkids.ui.parent.panels.UserControlPanel;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author baris
 */
public class ParentalControlPanel extends javax.swing.JPanel {

    /**
     * Creates new form ParentalControlPanel
     */
    public ParentalControlPanel() {
        setName("ParentalControl");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        ParentLabel = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        optionPanel = new javax.swing.JPanel();
        userButton = new javax.swing.JButton();
        editQbutton = new javax.swing.JButton();
        addQbutton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        changePassword = new javax.swing.JButton();
        editachievement = new javax.swing.JButton();
        highlight = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        backgroundLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(800, 600));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        ParentLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 30)); // NOI18N
        ParentLabel.setForeground(new java.awt.Color(255, 255, 255));
        ParentLabel.setText("Parental Controls");
        ParentLabel.setBounds(70, 180, 270, 90);
        jLayeredPane1.add(ParentLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        optionPanel.setOpaque(false);

        userButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        userButton.setForeground(new java.awt.Color(255, 255, 255));
        userButton.setText("Add/Delete Child");
        userButton.setBorderPainted(false);
        userButton.setContentAreaFilled(false);
        userButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userButton.setIconTextGap(0);
        userButton.setPreferredSize(new java.awt.Dimension(303, 33));
        userButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userButtonMouseExited(evt);
            }
        });
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });
        optionPanel.add(userButton);

        editQbutton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        editQbutton.setForeground(new java.awt.Color(255, 255, 255));
        editQbutton.setText("Edit Questions");
        editQbutton.setBorderPainted(false);
        editQbutton.setContentAreaFilled(false);
        editQbutton.setPreferredSize(new java.awt.Dimension(303, 33));
        editQbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editQbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editQbuttonMouseExited(evt);
            }
        });
        editQbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editQbuttonActionPerformed(evt);
            }
        });
        optionPanel.add(editQbutton);

        addQbutton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        addQbutton.setForeground(new java.awt.Color(255, 255, 255));
        addQbutton.setText("Add a New Question");
        addQbutton.setBorderPainted(false);
        addQbutton.setContentAreaFilled(false);
        addQbutton.setPreferredSize(new java.awt.Dimension(303, 33));
        addQbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addQbuttonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addQbuttonMouseEntered(evt);
            }
        });
        addQbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQbuttonActionPerformed(evt);
            }
        });
        optionPanel.add(addQbutton);

        resetButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset Game");
        resetButton.setBorderPainted(false);
        resetButton.setContentAreaFilled(false);
        resetButton.setPreferredSize(new java.awt.Dimension(303, 33));
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetButtonMouseEntered(evt);
            }
        });
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        optionPanel.add(resetButton);

        changePassword.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        changePassword.setForeground(new java.awt.Color(255, 255, 255));
        changePassword.setText("Change Password");
        changePassword.setBorderPainted(false);
        changePassword.setContentAreaFilled(false);
        changePassword.setPreferredSize(new java.awt.Dimension(303, 33));
        changePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changePasswordMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePasswordMouseEntered(evt);
            }
        });
        changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordActionPerformed(evt);
            }
        });
        optionPanel.add(changePassword);

        editachievement.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        editachievement.setForeground(new java.awt.Color(255, 255, 255));
        editachievement.setText("Edit Achievement");
        editachievement.setActionCommand("Edit Achienement");
        editachievement.setBorderPainted(false);
        editachievement.setContentAreaFilled(false);
        editachievement.setPreferredSize(new java.awt.Dimension(303, 33));
        editachievement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editachievementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editachievementMouseExited(evt);
            }
        });
        editachievement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editachievementActionPerformed(evt);
            }
        });
        optionPanel.add(editachievement);

        optionPanel.setBounds(0, 0, 310, 260);
        jLayeredPane3.add(optionPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        highlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/HighlightedButton.png"))); // NOI18N
        highlight.setBounds(50, 240, 303, 33);
        jLayeredPane3.add(highlight, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBounds(40, 280, 310, 240);
        jLayeredPane1.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLayeredPane2.setPreferredSize(new java.awt.Dimension(330, 370));
        jLayeredPane2.setRequestFocusEnabled(false);
        jLayeredPane2.setBounds(390, 160, 370, 370);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.PALETTE_LAYER);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/BasicScreen2.png"))); // NOI18N
        backgroundLabel.setBounds(0, 0, 800, 600);
        jLayeredPane1.add(backgroundLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        // TODO add your handling code here:
        this.highlight.setLocation(this.userButton.getLocation());
        
        jLayeredPane2.removeAll();
        jLayeredPane2.repaint();
        UserControlPanel uPanel = new UserControlPanel();
        jLayeredPane2.add(uPanel);
    }//GEN-LAST:event_userButtonActionPerformed

    private void userButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseEntered
        // TODO add your handling code here:
        userButton.setForeground(Color.yellow);
    }//GEN-LAST:event_userButtonMouseEntered

    private void userButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseExited
        // TODO add your handling code here:
        userButton.setForeground(Color.white);
    }//GEN-LAST:event_userButtonMouseExited

    private void editQbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editQbuttonMouseEntered
        // TODO add your handling code here:
        editQbutton.setForeground(Color.yellow);
    }//GEN-LAST:event_editQbuttonMouseEntered

    private void editQbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editQbuttonMouseExited
        // TODO add your handling code here:
        editQbutton.setForeground(Color.white);
    }//GEN-LAST:event_editQbuttonMouseExited

    private void resetButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseEntered
        // TODO add your handling code here:
        resetButton.setForeground(Color.yellow);
    }//GEN-LAST:event_resetButtonMouseEntered

    private void resetButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseExited
        // TODO add your handling code here:
        resetButton.setForeground(Color.white);
    }//GEN-LAST:event_resetButtonMouseExited

    private void editQbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editQbuttonActionPerformed
        // TODO add your handling code here:
        this.highlight.setLocation(this.editQbutton.getLocation());
        jLayeredPane2.removeAll();
        jLayeredPane2.repaint();
        EditQuestionsPanel editPanel = new EditQuestionsPanel();
        jLayeredPane2.add(editPanel);
    }//GEN-LAST:event_editQbuttonActionPerformed

    private void addQbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addQbuttonMouseExited
        // TODO add your handling code here:
        addQbutton.setForeground(Color.white);
    }//GEN-LAST:event_addQbuttonMouseExited

    private void addQbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addQbuttonMouseEntered
        // TODO add your handling code here:
        addQbutton.setForeground(Color.yellow);
    }//GEN-LAST:event_addQbuttonMouseEntered

    private void addQbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQbuttonActionPerformed
        // TODO add your handling code here:
        this.highlight.setLocation(this.addQbutton.getLocation());
        jLayeredPane2.removeAll();
        jLayeredPane2.repaint();
        AddQuestionPanel aPanel = new AddQuestionPanel();
        jLayeredPane2.add(aPanel);
    }//GEN-LAST:event_addQbuttonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        this.highlight.setLocation(this.resetButton.getLocation());
        jLayeredPane2.removeAll();
        jLayeredPane2.repaint();
        ResetGamePanel rPanel = new ResetGamePanel();
        jLayeredPane2.add(rPanel);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void changePasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordMouseExited
        // TODO add your handling code here:
        changePassword.setForeground(Color.white);
    }//GEN-LAST:event_changePasswordMouseExited

    private void changePasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordMouseEntered
        // TODO add your handling code here:
        changePassword.setForeground(Color.yellow);
    }//GEN-LAST:event_changePasswordMouseEntered

    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordActionPerformed
        // TODO add your handling code here:
        this.highlight.setLocation(this.changePassword.getLocation());
        jLayeredPane2.removeAll();
        jLayeredPane2.repaint();
        ChangePassPanel cPanel = new ChangePassPanel();
        jLayeredPane2.add(cPanel);
    }//GEN-LAST:event_changePasswordActionPerformed

    private void editachievementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editachievementMouseExited
        // TODO add your handling code here:
        editachievement.setForeground(Color.white);
    }//GEN-LAST:event_editachievementMouseExited

    private void editachievementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editachievementMouseEntered
        // TODO add your handling code here:
        editachievement.setForeground(Color.yellow);
    }//GEN-LAST:event_editachievementMouseEntered

    private void editachievementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editachievementActionPerformed
        this.highlight.setLocation(this.editachievement.getLocation());
        jLayeredPane2.removeAll();
        jLayeredPane2.repaint();
        EditAchievementPanel dPanel = new EditAchievementPanel();
        jLayeredPane2.add(dPanel);
    }//GEN-LAST:event_editachievementActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ParentLabel;
    private javax.swing.JButton addQbutton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton changePassword;
    private javax.swing.JButton editQbutton;
    private javax.swing.JButton editachievement;
    private javax.swing.JLabel highlight;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
}
